# Configuración para golangci-lint
version: 2
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - unconvert
    - unparam
    - prealloc
    - copyloopvar
    - gocritic

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
  exclude-dirs:
    - testdata
  exclude-files:
    - ".*\\.generated\\.go$"
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
